# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class userinfo(models.Model):
	user = models.CharField(max_length=30)
	passwd = models.CharField(max_length=30)


class customerService(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(primary_key = True, max_length=7, default = 'unknown')
	q1 = models.TextField(default = 0, max_length = 700, verbose_name = 'tell us what kind of job you want to do in future')
	q2 = models.TextField(default = 0, max_length = 2500, verbose_name = 'translation')
	q3 = models.TextField(default = 0, max_length = 2200, verbose_name = 'essay about candidate name')

class consultencyService(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(primary_key = True, max_length=7, default = 'unknown')
	q1 = models.TextField(default = 0, max_length = 500, verbose_name = '你认为准留学生群体选择留学机构的标准有哪些')
	q2 = models.TextField(default = 0, max_length = 500, verbose_name = '查看公司网站，用自己的语言概括公司的特点和优势')
	q3 = models.TextField(default = 0, max_length = 500, verbose_name = '如果客户没赴约，你会采取什么措施')
	q4 = models.TextField(default = 0, max_length = 500, verbose_name = '你在成长中遇到过的最大的挑战是什么，你是如何克服的，从中你学到了什么')
	q5 = models.TextField(default = 0, max_length = 500, verbose_name = '公司将在某大学举办一次宣讲活动，在此次活动中将包括宣讲师，PPT制作者，物料运送和采购专员，现场秩序协调员，和主持人。你希望在此活动中担任什么角色？为什么？')

class generic(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(primary_key = True, max_length=7, default = 'unknown')
	q1 = models.PositiveIntegerField(default = 0)
	q2 = models.PositiveIntegerField(default = 0) 
	q3 = models.PositiveIntegerField(default = 0) 
	q4 = models.PositiveIntegerField(default = 0) 
	q5 = models.PositiveIntegerField(default = 0) 
	q6 = models.PositiveIntegerField(default = 0) 
	q7 = models.PositiveIntegerField(default = 0) 
	q8 = models.PositiveIntegerField(default = 0) 
	q9 = models.PositiveIntegerField(default = 0) 

	c1 = models.BooleanField(default = False,verbose_name='我喜欢完成具有重大意义的事情')
	c2 = models.BooleanField(default = False,verbose_name='我喜欢在某些职业专业或专门项目上自己是公认的权威')
	c3 = models.BooleanField(default = False,verbose_name='我喜欢能够自豪地说我将一件难题成功地处理了')
	c4 = models.BooleanField(default = False,verbose_name='我喜欢解答其他人觉得很困难的谜语与问题')
	c5 = models.BooleanField(default = False,verbose_name='我喜欢完成别人认为需要技巧和努力的工作')
	c6 = models.BooleanField(default = False,verbose_name='我喜欢探求伟人对我所感兴趣的各种问题有什么看法')
	c7 = models.BooleanField(default = False,verbose_name='我喜欢读伟人的故事')
	c8 = models.BooleanField(default = False,verbose_name='我喜欢遵从习俗，并避免做我所尊敬的人认为不合常规的事')
	c9 = models.BooleanField(default = False,verbose_name='我喜欢遵照指示去做我所该做的事')
	c10 = models.BooleanField(default = False,verbose_name='在团体中，我喜欢接受别人的领导来决定团体该作什么')
	c11 = models.BooleanField(default = False,verbose_name='作计划时，我喜欢从其见解为我所尊敬的人那里得到些建议')
	c12 = models.BooleanField(default = False,verbose_name='我喜欢接受我所尊敬的人领导')
	c13 = models.BooleanField(default = False,verbose_name='我喜欢称赞我所仰慕的人')
	c14 = models.BooleanField(default = False,verbose_name='我喜欢我写的所有的东西都很精确、清楚、有条有理')
	c15 = models.BooleanField(default = False,verbose_name='对我所承担的任何工作，我喜欢对其细节作好计划与组织')
	c16 = models.BooleanField(default = False,verbose_name='我喜欢遵从指示做我所该做的事')
	c17 = models.BooleanField(default = False,verbose_name='我喜欢在工作开始之前对工作做好组织和计划')
	c18 = models.BooleanField(default = False,verbose_name='假如我必须旅行时，我喜欢把事情事先安排好')
	c19 = models.BooleanField(default = False,verbose_name='我喜欢将我开了头的工作或任务完成')
	c20 = models.BooleanField(default = False,verbose_name='我喜欢保持我的书桌或工作间的清洁与整齐')

	c21 = models.BooleanField(default = False,verbose_name='我喜欢饮食有规律，并且有固定时间吃东西')
	c22 = models.BooleanField(default = False,verbose_name='我喜欢将我的信、帐单和其他文件整齐地排列着并以某种系统存档')
	c23 = models.BooleanField(default = False,verbose_name='我喜欢在宴会上讲些趣事与笑话')
	c24 = models.BooleanField(default = False,verbose_name='在公共场合中，我喜欢人们注意和评价我的外表')
	c25 = models.BooleanField(default = False,verbose_name='我喜欢提出明知没有人能回答得出来的问题')
	c26 = models.BooleanField(default = False,verbose_name='我喜欢说别人认为机智与聪明的事')
	c27 = models.BooleanField(default = False,verbose_name='我喜欢在团体中成为众目所瞩的对象')
	c28 = models.BooleanField(default = False,verbose_name='我喜欢用些别人常常不明白其意义的字眼')
	c29 = models.BooleanField(default = False,verbose_name='我喜欢对别人谈我所经历的冒险与奇特的事')
	c30 = models.BooleanField(default = False,verbose_name='我有时喜欢做些事，只为了想看别人对此事的反应')
	c31 = models.BooleanField(default = False,verbose_name='我喜欢谈我的成就')
	c32 = models.BooleanField(default = False,verbose_name='我喜欢能随我的意志来去自如')
	c33 = models.BooleanField(default = False,verbose_name='我喜欢很自如地做我想做的事')
	c34 = models.BooleanField(default = False,verbose_name='我希望独立决定我要做的事')
	c35 = models.BooleanField(default = False,verbose_name='我喜欢批判权威人士')
	c36 = models.BooleanField(default = False,verbose_name='我喜欢回避责任与义务')
	c37 = models.BooleanField(default = False,verbose_name='我喜欢表达我对事情的看法')
	c38 = models.BooleanField(default = False,verbose_name='我喜欢做些别人认为不合常规的事')
	c39 = models.BooleanField(default = False,verbose_name='我喜欢避免需要依常规做事的场合')
	c40 = models.BooleanField(default = False,verbose_name='我喜欢依我的方式做事而不在乎别人的看法')

	c41 = models.BooleanField(default = False,verbose_name='我喜欢结交新朋友')
	c42 = models.BooleanField(default = False,verbose_name='我喜欢与朋友有深厚的友谊')
	c43 = models.BooleanField(default = False,verbose_name='我喜欢广交朋友')
	c44 = models.BooleanField(default = False,verbose_name='我喜欢写信给我的朋友')
	c45 = models.BooleanField(default = False,verbose_name='我喜欢与朋友分享一切')
	c46 = models.BooleanField(default = False,verbose_name='我喜欢为我的朋友做事')
	c47 = models.BooleanField(default = False,verbose_name='我喜欢对我的朋友们忠诚')
	c48 = models.BooleanField(default = False,verbose_name='我喜欢参与那些成员之间具有温暖与友善情感的团体')
	c49 = models.BooleanField(default = False,verbose_name='我比较喜欢与朋友共事而不喜欢独自工作')
	c50 = models.BooleanField(default = False,verbose_name='我喜欢就一个人为什么那样做去判断他，而不从他实际上做什么去判断他')

	c51 = models.BooleanField(default = False,verbose_name='我喜欢了解我的朋友们在面临各种问题时的感觉')
	c52 = models.BooleanField(default = False,verbose_name='我喜欢研究与分析别人的行为')
	c53 = models.BooleanField(default = False,verbose_name='我喜欢将自己放在别人的立场上，看自己若处在相同的情境会有什么感觉')
	c54 = models.BooleanField(default = False,verbose_name='我喜欢分析我自己的动机与情感')
	c55 = models.BooleanField(default = False,verbose_name='我喜欢预测我的朋友们在各种情况下的反应')
	c56 = models.BooleanField(default = False,verbose_name='我喜欢观察别人在某些情况下的感觉')
	c57 = models.BooleanField(default = False,verbose_name='我喜欢观察我的朋友们的性格并尝试找出使他们成为这样的原因')
	c58 = models.BooleanField(default = False,verbose_name='我喜欢我的朋友对我仁慈')
	c59 = models.BooleanField(default = False,verbose_name='当我受伤或生病时，我喜欢我的朋友为此小题大作')
	c60 = models.BooleanField(default = False,verbose_name='当我有麻烦时，我喜欢我的朋友帮助我')

	c61 = models.BooleanField(default = False,verbose_name='我喜欢我的朋友们对我有深情')
	c62 = models.BooleanField(default = False,verbose_name='当我生病时，我喜欢朋友们为我感伤')
	c63 = models.BooleanField(default = False,verbose_name='我喜欢我的朋友高兴地为我办点小事')
	c64 = models.BooleanField(default = False,verbose_name='当我沮丧时，我喜欢我的朋友们同情我，并使我愉快')
	c65 = models.BooleanField(default = False,verbose_name='当我失败时，我喜欢我的朋友们鼓励我')
	c66 = models.BooleanField(default = False,verbose_name='当我有问题时，我喜欢我的朋友们能同情与了解')
	c67 = models.BooleanField(default = False,verbose_name='当作为群众团体的一个成员时，我喜欢被指定或选为领导者')
	c68 = models.BooleanField(default = False,verbose_name='只要可能，我喜欢监督与指导别人的行动')
	c69 = models.BooleanField(default = False,verbose_name='我喜欢成为我所属的机构与团体的领导之一')
	c70 = models.BooleanField(default = False,verbose_name='我喜欢告诉别人怎么做他们的工作')

	c71 = models.BooleanField(default = False,verbose_name='我喜欢被人们叫去做和事佬')
	c72 = models.BooleanField(default = False,verbose_name='当我的观点被攻击时，我喜欢为之辩护')
	c73 = models.BooleanField(default = False,verbose_name='我喜欢能说服与影响其他人去做他们的工作')
	c74 = models.BooleanField(default = False,verbose_name='在团体中，我喜欢决定我们该做什么')
	c75 = models.BooleanField(default = False,verbose_name='我喜欢被人当作领导')
	c76 = models.BooleanField(default = False,verbose_name='每当我做错了事，我感到有罪恶感')
	c77 = models.BooleanField(default = False,verbose_name='我觉得我必须承认我所做的一些错事')
	c78 = models.BooleanField(default = False,verbose_name='我觉得样样不如人')
	c79 = models.BooleanField(default = False,verbose_name='在我认为是我上司的人面前，我感到胆怯')
	c80 = models.BooleanField(default = False,verbose_name='我知道自己做错了些事时会感到内疚')
	c81 = models.BooleanField(default = False,verbose_name='由于自己无能力处理各种情况使我感到沮丧')
	c82 = models.BooleanField(default = False,verbose_name='当我退让或避免争执时，我感到比争取达到目的时还好些')
	c83 = models.BooleanField(default = False,verbose_name='当我做错事时，我觉得我比任何人都更该受到责备')
	c84 = models.BooleanField(default = False,verbose_name='我觉得我所受的痛苦与不幸是好处多于坏处')
	c85 = models.BooleanField(default = False,verbose_name='我喜欢帮助比我不幸的人')
	c86 = models.BooleanField(default = False,verbose_name='我喜欢对朋友们慷慨')
	c87 = models.BooleanField(default = False,verbose_name='我喜欢为我的朋友做点小事')
	c88 = models.BooleanField(default = False,verbose_name='我喜欢我的朋友信任我，并对我倾诉他们的麻烦')
	c89 = models.BooleanField(default = False,verbose_name='我喜欢原谅有时可能伤害了我的朋友')
	c90 = models.BooleanField(default = False,verbose_name='当我的朋友有麻烦时，我喜欢帮助他们')
	c91 = models.BooleanField(default = False,verbose_name='当我的朋友受伤时，我喜欢同情他们')
	c92 = models.BooleanField(default = False,verbose_name='我喜欢待人以仁慈与同情')
	c93 = models.BooleanField(default = False,verbose_name='我喜欢对我的朋友表示自己的深情')
	c94 = models.BooleanField(default = False,verbose_name='我喜欢在新奇的餐厅里吃饭')
	c95 = models.BooleanField(default = False,verbose_name='我喜欢旅行和到处观光')
	c96 = models.BooleanField(default = False,verbose_name='我喜欢搬家，住在不同的地方')
	c97 = models.BooleanField(default = False,verbose_name='我喜欢做些新鲜且有变化的事')
	c98 = models.BooleanField(default = False,verbose_name='我喜欢试验与尝试新东西')
	c99 = models.BooleanField(default = False,verbose_name='我喜欢尝试新职业，而不喜欢一直做同样的老事情')
	c100 = models.BooleanField(default = False,verbose_name='我喜欢见些原来不熟悉的人')
	c101 = models.BooleanField(default = False,verbose_name='我喜欢在日常生活中经历新奇与变迁')
	c102 = models.BooleanField(default = False,verbose_name='我喜欢追求新潮流与时髦')
	c103 = models.BooleanField(default = False,verbose_name='对我所承担的事，我喜欢认真去做')
	c104 = models.BooleanField(default = False,verbose_name='我喜欢在接受其他事之前完成手头的事')
	c105 = models.BooleanField(default = False,verbose_name='我喜欢继续解我的难题或问题，直到解决为止')
	c106 = models.BooleanField(default = False,verbose_name='我喜欢固定在某一职业或问题上，甚至看来它好象没有什么希望')
	c107 = models.BooleanField(default = False,verbose_name='我喜欢不受干扰地长时间工作')
	c108 = models.BooleanField(default = False,verbose_name='当我工作时，我喜欢避开干扰')
	c109 = models.BooleanField(default = False,verbose_name='我喜欢熬夜将工作完成')
	c110 = models.BooleanField(default = False,verbose_name='我喜欢长时间地工作而不受别人干扰')
	c111 = models.BooleanField(default = False,verbose_name='我喜欢将我开了头的任何事情或工作完成')
	c112 = models.BooleanField(default = False,verbose_name='假如某人罪有应得的话我想公开的进行批评')
	c113 = models.BooleanField(default = False,verbose_name='当我动怒时，我想摔东西')
	c114 = models.BooleanField(default = False,verbose_name='我喜欢对别人说我对他们的看法')
	c115 = models.BooleanField(default = False,verbose_name='我想取笑那些我认为他们行为愚蠢的人')
	c116 = models.BooleanField(default = False,verbose_name='我喜欢攻击与我观点相反的看法')
	c117 = models.BooleanField(default = False,verbose_name='当事情不顺时，我想责怪别人')
	c118 = models.BooleanField(default = False,verbose_name='当有人侮辱我时，我想报复')
	c119 = models.BooleanField(default = False,verbose_name='当我不赞同他们的看法时，我喜欢说服他们')

