# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class userinfo(models.Model):
	user = models.CharField(max_length=30)
	passwd = models.CharField(max_length=30)


class customerService(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(primary_key = True, max_length=7, default = 'unknown')
	q1 = models.TextField(default = 0, max_length = 700)
	q2 = models.TextField(default = 0, max_length = 2500)
	q3 = models.TextField(default = 0, max_length = 2200)

class consultencyService(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(primary_key = True, max_length=7, default = 'unknown')
	q1 = models.TextField(default = 0, max_length = 500)
	q2 = models.TextField(default = 0, max_length = 500)
	q3 = models.TextField(default = 0, max_length = 500)
	q4 = models.TextField(default = 0, max_length = 500)
	q5 = models.TextField(default = 0, max_length = 500)

class generic(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(primary_key = True, max_length=7, default = 'unknown')
	q1 = models.PositiveIntegerField(default = 0)
	q2 = models.PositiveIntegerField(default = 0) 
	q3 = models.PositiveIntegerField(default = 0) 
	q4 = models.PositiveIntegerField(default = 0) 
	q5 = models.PositiveIntegerField(default = 0) 
	q6 = models.PositiveIntegerField(default = 0) 
	q7 = models.PositiveIntegerField(default = 0) 
	q8 = models.PositiveIntegerField(default = 0) 
	q9 = models.PositiveIntegerField(default = 0) 

	c1 = models.BooleanField(default = False)
	c2 = models.BooleanField(default = False)
	c3 = models.BooleanField(default = False)
	c4 = models.BooleanField(default = False)
	c5 = models.BooleanField(default = False)
	c6 = models.BooleanField(default = False)
	c7 = models.BooleanField(default = False)
	c8 = models.BooleanField(default = False)
	c9 = models.BooleanField(default = False)
	c10 = models.BooleanField(default = False)
	c11 = models.BooleanField(default = False)
	c12 = models.BooleanField(default = False)
	c13 = models.BooleanField(default = False)
	c14 = models.BooleanField(default = False)
	c15 = models.BooleanField(default = False)
	c16 = models.BooleanField(default = False)
	c17 = models.BooleanField(default = False)
	c18 = models.BooleanField(default = False)
	c19 = models.BooleanField(default = False)
	c20 = models.BooleanField(default = False)

	c21 = models.BooleanField(default = False)
	c22 = models.BooleanField(default = False)
	c23 = models.BooleanField(default = False)
	c24 = models.BooleanField(default = False)
	c25 = models.BooleanField(default = False)
	c26 = models.BooleanField(default = False)
	c27 = models.BooleanField(default = False)
	c28 = models.BooleanField(default = False)
	c29 = models.BooleanField(default = False)
	c30 = models.BooleanField(default = False)
	c31 = models.BooleanField(default = False)
	c32 = models.BooleanField(default = False)
	c33 = models.BooleanField(default = False)
	c34 = models.BooleanField(default = False)
	c35 = models.BooleanField(default = False)
	c36 = models.BooleanField(default = False)
	c37 = models.BooleanField(default = False)
	c38 = models.BooleanField(default = False)
	c39 = models.BooleanField(default = False)
	c40 = models.BooleanField(default = False)

	c41 = models.BooleanField(default = False)
	c42 = models.BooleanField(default = False)
	c43 = models.BooleanField(default = False)
	c44 = models.BooleanField(default = False)
	c45 = models.BooleanField(default = False)
	c46 = models.BooleanField(default = False)
	c47 = models.BooleanField(default = False)
	c48 = models.BooleanField(default = False)
	c49 = models.BooleanField(default = False)
	c50 = models.BooleanField(default = False)

	c51 = models.BooleanField(default = False)
	c52 = models.BooleanField(default = False)
	c53 = models.BooleanField(default = False)
	c54 = models.BooleanField(default = False)
	c55 = models.BooleanField(default = False)
	c56 = models.BooleanField(default = False)
	c57 = models.BooleanField(default = False)
	c58 = models.BooleanField(default = False)
	c59 = models.BooleanField(default = False)
	c60 = models.BooleanField(default = False)

	c61 = models.BooleanField(default = False)
	c62 = models.BooleanField(default = False)
	c63 = models.BooleanField(default = False)
	c64 = models.BooleanField(default = False)
	c65 = models.BooleanField(default = False)
	c66 = models.BooleanField(default = False)
	c67 = models.BooleanField(default = False)
	c68 = models.BooleanField(default = False)
	c69 = models.BooleanField(default = False)
	c70 = models.BooleanField(default = False)

	c71 = models.BooleanField(default = False)
	c72 = models.BooleanField(default = False)
	c73 = models.BooleanField(default = False)
	c74 = models.BooleanField(default = False)
	c75 = models.BooleanField(default = False)
	c76 = models.BooleanField(default = False)
	c77 = models.BooleanField(default = False)
	c78 = models.BooleanField(default = False)
	c79 = models.BooleanField(default = False)
	c80 = models.BooleanField(default = False)
	c81 = models.BooleanField(default = False)
	c82 = models.BooleanField(default = False)
	c83 = models.BooleanField(default = False)
	c84 = models.BooleanField(default = False)
	c85 = models.BooleanField(default = False)
	c86 = models.BooleanField(default = False)
	c87 = models.BooleanField(default = False)
	c88 = models.BooleanField(default = False)
	c89 = models.BooleanField(default = False)
	c90 = models.BooleanField(default = False)
	c91 = models.BooleanField(default = False)
	c92 = models.BooleanField(default = False)
	c93 = models.BooleanField(default = False)
	c94 = models.BooleanField(default = False)
	c95 = models.BooleanField(default = False)
	c96 = models.BooleanField(default = False)
	c97 = models.BooleanField(default = False)
	c98 = models.BooleanField(default = False)
	c99 = models.BooleanField(default = False)
	c100 = models.BooleanField(default = False)
	c101 = models.BooleanField(default = False)
	c102 = models.BooleanField(default = False)
	c103 = models.BooleanField(default = False)
	c104 = models.BooleanField(default = False)
	c105 = models.BooleanField(default = False)
	c106 = models.BooleanField(default = False)
	c107 = models.BooleanField(default = False)
	c108 = models.BooleanField(default = False)
	c109 = models.BooleanField(default = False)
	c110 = models.BooleanField(default = False)
	c111 = models.BooleanField(default = False)
	c112 = models.BooleanField(default = False)
	c113 = models.BooleanField(default = False)
	c114 = models.BooleanField(default = False)
	c115 = models.BooleanField(default = False)
	c116 = models.BooleanField(default = False)
	c117 = models.BooleanField(default = False)
	c118 = models.BooleanField(default = False)
	c119 = models.BooleanField(default = False)

